AWSTemplateFormatVersion: '2012-10-17'
Description: "TP AWS Lambda - Code Chargé depuis src/main.py"

Parameters:
  Environment:
    Type: String
    Description: "Nom de l'environnement (dev, staging, prod)"
    Default: "fgbossou"
  BucketName:
    Type: String
    Description: "Nom du bucket S3 pour stocker le code de la fonction Lambda"
    Default: "iabd-sourcecode-management-bucket"

  Resources:
    LambdaExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        # RoleName: !Sub "${Environment}-LambdaExecutionRole"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service: [lambda.amazonaws.com]
              Action: [sts:AssumeRole]
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
          # - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        Policies:
          - PolicyName: !Sub "${Environment}-LambdaS3AccessPolicy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Deny
                  Action: [s3:GetObject, s3:PutObject]
                  Resource: !Sub 'arn:aws:s3:::${Environment}-${BucketName}/*' 

    # Fonction Lambda pour gérer les events S3
    LambdaTrigger:
      Type: AWS::Lambda::Function
      Properties:
        FunctionName: !Sub "${Environment}-S3LambdaTrigger"
        Handler: main.lambda_handler
        Role: !GetAtt LambdaExecutionRole.Arn
        Runtime: python3.12
        Code: ../src

    # S3 Bucket pour stocker les fichiers
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Sub "${Environment}-${BucketName}"
        NotificationConfiguration:
          LambdaConfigurations:
            - Event: "s3:ObjectCreated:*"
              # Filter:
              #   S3Key:
              #     Rules:
              #       - Name: suffix
              #         Value: ".txt"
              Function: !GetAtt LambdaTriggerFunction.Arn